In [17]:
import numpy as np


# Perceptron initiation

In [18]:
# Construct the OR dataset
X =np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([[0], [1], [1], [1]])

In [19]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [20]:
X.shape

(4, 2)

In [21]:

X.shape[0]

4

In [22]:
X.shape[1]

2

In [23]:
y

array([[0],
       [1],
       [1],
       [1]])

In [24]:
y.shape

(4, 1)

In [25]:
# # Initilize the weight matrix and store the learning rate
# # N refer to the number of culumns in our input feature vectors
# # alpha is our learning rate for the perceptron algorithm => normaly alpha = 0.1, 0.01, 0.001
# # W is our weight matrix with random values sampled from a normal (Gaussian) distribution with mean zero and unit variance
# # W will have N + 1 entries one for each of the N inputs in the feature vector plus one for the bias
# # W is divided by the square_root of the number of inputs, a common technique used to scale our weight matrix (faster convergence).
# N = X.shape[1]
# Weights = np.random.randn(N + 1) / np.sqrt(N)
# alpha = 0.1

In [26]:
# Weights

In [27]:
# # Define step function
# def step(x):
#     return 1 if x > 0 else 0

In [28]:
# # Define a training procedure fit
# def fit(X, y, epochs=10):
#     # insert a colums of 1's as the last entry in the feature matrix, in order to treat the bias as a trainable parameter within W
#     X = np.c_[X, np.ones((X.shape[0]))]
#     W = Weights
    
#     # Loop over the desired number of epochs
#     for epoch in np.arange(0, epochs):
#         # loop over each individual data point
#         for (x, target) in zip(X, y):
#             # take the dot product btn the input features and the W, the pass this value through the step function to obtain prediction
#             p = step(np.dot(x, W))
            
#             # restrict to perform a weight update if our prediction does not match the target
#             if p != target:
#                 error = p - target
#                 # update W
#                 W += -alpha * error * x
#                 print("[UPDATED] weights... ", W)
#         Weights = W

In [29]:
# # Define predict method to predict the class labels for a given set of input data
# # Note: obtaining the output prediction for X is the same as the training procedure
# def predict(X, addBias=True):
#     # ensure our input is matrix
#     X = np.atleast_2d(X)
#     W = Weights
    
#     # check to see if the bias column should be added
#     if addBias:
#         #i nsert a columns of 1's as the last enry in the feature matrix
#         X = np.c_[X, np.ones((X.shape[0]))]
    
#     # take the dot product between the input features and the weight matrix, then pass the value through the step function
#     return step(np.dot(X, W))

# Evaluating the perceptron bitwise dataset

In [30]:
# # Training our perceptron
# print("[INFO] training perceptron...")
# fit(X, y, epochs=20)

In [31]:
# # Evaluate our trained perceptron
# print("[INFO] testing perceptron...")

# # Evaluation is done by looping over the data points 
# for (x, target) in zip(X, y):
#     pred = predict(x)
#     print("[INFO] data={}, ground_truth={}, pred={}".format(x, target[0], pred))

# AND OPERATION

In [32]:
# AND operation classification with object oriented
class Perceptron:
    def __init__(self, N, alpha=0.1):
        # initialize the weight matrix and strore the learning rate
        self.W = np.random.randn(N + 1) /np.sqrt(N)
        self.alpha = alpha
        
    def step(self, x):
        return 1 if x >0 else 0
    
    def fit(self, X, y, epochs=10):
        # insert column of 1's as the last enry in the feature matrix
        X =np.c_[X, np.ones((X.shape[0]))]
        
        for epoch in np.arange(0, epochs):
            for (x, target) in zip(X, y):
                # Obtain prediction by taking the dot product of the input features and weight matrix
                p = self.step(np.dot(x, self.W))
                
                # Perform weight update only when a weight update does not match the target
                if p != target:
                    error = p - target
                    self.W += -self.alpha * error * x
                    print("[UPDATED] weights..... ", self.W)
    
    def predict(self, X, addBias=True):
        # Ensuring that X is a matrix
        X =np.atleast_2d(X)
        
        if addBias:
            X = np.c_[X, np.ones((X.shape[0]))]
        
        return self.step(np.dot(X, self.W))
        

In [33]:
# Constructing AND dataset
X =np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([[0], [0], [0], [1]])

In [34]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [35]:
X.shape

(4, 2)

In [36]:
X.shape[0]

4

In [37]:
X.shape[1]

2

In [38]:
y

array([[0],
       [0],
       [0],
       [1]])

In [39]:
y.shape

(4, 1)

In [40]:
# Define out perceptron and train it
p = Perceptron(X.shape[1], alpha=0.1)
p.fit(X, y, epochs=20)

[UPDATED] weights.....  [-0.75036133 -0.70196433 -0.37902387]
[UPDATED] weights.....  [-0.65036133 -0.60196433 -0.27902387]
[UPDATED] weights.....  [-0.55036133 -0.50196433 -0.17902387]
[UPDATED] weights.....  [-0.45036133 -0.40196433 -0.07902387]
[UPDATED] weights.....  [-0.35036133 -0.30196433  0.02097613]
[UPDATED] weights.....  [-0.35036133 -0.30196433 -0.07902387]
[UPDATED] weights.....  [-0.25036133 -0.20196433  0.02097613]
[UPDATED] weights.....  [-0.25036133 -0.20196433 -0.07902387]
[UPDATED] weights.....  [-0.15036133 -0.10196433  0.02097613]
[UPDATED] weights.....  [-0.15036133 -0.10196433 -0.07902387]
[UPDATED] weights.....  [-0.05036133 -0.00196433  0.02097613]
[UPDATED] weights.....  [-0.05036133 -0.00196433 -0.07902387]
[UPDATED] weights.....  [0.04963867 0.09803567 0.02097613]
[UPDATED] weights.....  [ 0.04963867  0.09803567 -0.07902387]
[UPDATED] weights.....  [ 0.04963867 -0.00196433 -0.17902387]
[UPDATED] weights.....  [ 0.14963867  0.09803567 -0.07902387]
[UPDATED] w

In [41]:
# Evaluation
print("[INFO] testing perceptron...")
for (x, target) in zip(X, y):
    pred = p.predict(x)
    print("[INFO] data={}, ground_truth={}, pred={}".format(x, target[0], pred))

[INFO] testing perceptron...
[INFO] data=[0 0], ground_truth=0, pred=0
[INFO] data=[0 1], ground_truth=0, pred=0
[INFO] data=[1 0], ground_truth=0, pred=0
[INFO] data=[1 1], ground_truth=1, pred=1


# OR operation

In [42]:
# Constructing a dataset
X =np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([[0], [1], [1], [1]])

# Defining the perceptron and train it
m = Perceptron(X.shape[1], alpha=0.1)
print("[INFO] training the perceptron...")
m.fit(X, y, epochs=20)

[INFO] training the perceptron...
[UPDATED] weights.....  [-0.89182738 -0.15244416  1.34324714]
[UPDATED] weights.....  [-0.89182738 -0.15244416  1.24324714]
[UPDATED] weights.....  [-0.89182738 -0.15244416  1.14324714]
[UPDATED] weights.....  [-0.89182738 -0.15244416  1.04324714]
[UPDATED] weights.....  [-0.79182738 -0.05244416  1.14324714]
[UPDATED] weights.....  [-0.79182738 -0.05244416  1.04324714]
[UPDATED] weights.....  [-0.79182738 -0.05244416  0.94324714]
[UPDATED] weights.....  [-0.79182738 -0.05244416  0.84324714]
[UPDATED] weights.....  [-0.69182738  0.04755584  0.94324714]
[UPDATED] weights.....  [-0.69182738  0.04755584  0.84324714]
[UPDATED] weights.....  [-0.69182738  0.04755584  0.74324714]
[UPDATED] weights.....  [-0.69182738  0.04755584  0.64324714]
[UPDATED] weights.....  [-0.59182738  0.04755584  0.74324714]
[UPDATED] weights.....  [-0.59182738  0.04755584  0.64324714]
[UPDATED] weights.....  [-0.59182738  0.04755584  0.54324714]
[UPDATED] weights.....  [-0.49182738

In [43]:
# Evaluate
print("[INFO] testing the perceptron")
for (x, target) in zip(X, y):
    pred = m.predict(x)
    print("[INFO] data={}, ground_truth={}, pred={}".format(x, target[0], pred))

[INFO] testing the perceptron
[INFO] data=[0 0], ground_truth=0, pred=1
[INFO] data=[0 1], ground_truth=1, pred=1
[INFO] data=[1 0], ground_truth=1, pred=1
[INFO] data=[1 1], ground_truth=1, pred=1


# XOR nonlineary separable operation

In [44]:
# Construct a dataset
X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([[0], [1], [1], [0]])

# Define Perceptron and Train it
k = Perceptron(X.shape[1], alpha=0.1)
print("[INFO] training the perceptron...")
k.fit(X, y, epochs=20)

[INFO] training the perceptron...
[UPDATED] weights.....  [-0.26906775 -0.98942244  0.02323836]
[UPDATED] weights.....  [-0.16906775 -0.98942244  0.12323836]
[UPDATED] weights.....  [-0.16906775 -0.98942244  0.02323836]
[UPDATED] weights.....  [-0.16906775 -0.88942244  0.12323836]
[UPDATED] weights.....  [-0.06906775 -0.88942244  0.22323836]
[UPDATED] weights.....  [-0.06906775 -0.88942244  0.12323836]
[UPDATED] weights.....  [-0.06906775 -0.78942244  0.22323836]
[UPDATED] weights.....  [-0.06906775 -0.78942244  0.12323836]
[UPDATED] weights.....  [-0.06906775 -0.68942244  0.22323836]
[UPDATED] weights.....  [-0.06906775 -0.68942244  0.12323836]
[UPDATED] weights.....  [-0.06906775 -0.58942244  0.22323836]
[UPDATED] weights.....  [-0.06906775 -0.58942244  0.12323836]
[UPDATED] weights.....  [-0.06906775 -0.48942244  0.22323836]
[UPDATED] weights.....  [-0.06906775 -0.48942244  0.12323836]
[UPDATED] weights.....  [-0.06906775 -0.38942244  0.22323836]
[UPDATED] weights.....  [-0.06906775

In [45]:
# Evaluate the perceptron
print("[INFO] testing the perceptron...")
for (x, target) in zip(X, y):
    pred = k.predict(x)
    print("[INFO] data={}, ground_truth={}, pred={}".format(x, target[0], pred))

[INFO] testing the perceptron...
[INFO] data=[0 0], ground_truth=0, pred=1
[INFO] data=[0 1], ground_truth=1, pred=0
[INFO] data=[1 0], ground_truth=1, pred=0
[INFO] data=[1 1], ground_truth=0, pred=0


# Conclusion

In [ ]:
This illustrate a single layer network commonly known as perceptron.
The percetron is used to model bitwise operation OR and AND successfully since they are linearly separable
But the perceptron fail to model bitwise operation XOR because this is a nonlinearly separable operation. Hence require multiple layers.
